package com.frauddetection.alert.fdp28;

public enum FailureInjectionPoint {
    AFTER_COMMAND_CREATED,
    AFTER_COMMAND_CLAIMED,
    AFTER_ATTEMPTED_AUDIT,
    DURING_LOCAL_TRANSACTION,
    AFTER_BUSINESS_MUTATION,
    AFTER_OUTBOX_WRITTEN,
    AFTER_LOCAL_COMMIT_MARKER,
    DURING_SUCCESS_AUDIT,
    AFTER_RESPONSE_SNAPSHOT,
    DURING_BROKER_PUBLISH_ATTEMPT,
    DURING_EXTERNAL_ANCHOR_PUBLISH_ATTEMPT,
    DURING_PROJECTION_UPDATE,
    DURING_SENSITIVE_READ_AUDIT
}
