package com.frauddetection.alert.regulated.chaos;

public enum RegulatedMutationChaosWindow {
    AFTER_CLAIM_BEFORE_ATTEMPTED_AUDIT,
    AFTER_ATTEMPTED_AUDIT_BEFORE_BUSINESS_MUTATION,
    LEGACY_BUSINESS_COMMITTING,
    LEGACY_SUCCESS_AUDIT_PENDING,
    FDP29_FINALIZING,
    FDP29_FINALIZED_EVIDENCE_PENDING_EXTERNAL,
    LONG_RUNNING_PROCESSING_AFTER_CHECKPOINT_RENEWAL,
    EXPIRED_PROCESSING_AFTER_KILL,
    OUTBOX_CONFIRMATION_UNKNOWN_AFTER_RESTART,
    RECOVERY_STATE_WITH_STALE_SNAPSHOT
}
