package com.frauddetection.alert.regulated.chaos;

public enum RegulatedMutationChaosWindow {
    AFTER_CLAIM_BEFORE_EVIDENCE_PREPARATION,
    AFTER_ATTEMPTED_AUDIT_BEFORE_EVIDENCE_PREPARATION,
    LIVE_IN_FLIGHT_BEFORE_EVIDENCE_GATED_FINALIZE,
    EVIDENCE_GATED_FINALIZING,
    FINALIZE_RECOVERY_REQUIRED,
    FINALIZED_EVIDENCE_PENDING_EXTERNAL,
    LONG_RUNNING_PROCESSING_AFTER_CHECKPOINT_RENEWAL,
    EXPIRED_PROCESSING_AFTER_KILL,
    OUTBOX_CONFIRMATION_UNKNOWN_AFTER_RESTART,
    RECOVERY_STATE_WITH_STALE_SNAPSHOT,
    BEFORE_EVIDENCE_PREPARATION,
    AFTER_EVIDENCE_PREPARED_BEFORE_FINALIZE,
    FINALIZED_VISIBLE_LOCAL_COMMIT,
    BEFORE_EVIDENCE_GATED_FINALIZE
}
