package com.frauddetection.alert.regulated.chaos;

public enum RegulatedMutationProofLevel {
    REAL_ALERT_SERVICE_KILL,
    REAL_ALERT_SERVICE_JVM_KILL,
    REAL_ALERT_SERVICE_RESTART_API_PROOF,
    LIVE_IN_FLIGHT_REQUEST_KILL,
    PRODUCTION_IMAGE_CONTAINER_KILL,
    PRODUCTION_IMAGE_RESTART_API_PROOF,
    DURABLE_STATE_SEEDED_CONTAINER_PROOF,
    DUMMY_CONTAINER_DURABLE_STATE_PROOF,
    MODELED_DURABLE_STATE_PROOF,
    API_PERSISTED_STATE_PROOF
}
