package com.frauddetection.alert.audit;

public enum AuditAction {
    SUBMIT_ANALYST_DECISION,
    UPDATE_FRAUD_CASE,
    READ_AUDIT_EVENTS,
    VERIFY_AUDIT_INTEGRITY,
    VERIFY_EXTERNAL_AUDIT_INTEGRITY,
    EXPORT_AUDIT_EVIDENCE
}
