package com.frauddetection.alert.audit;

public enum AuditResourceType {
    ALERT,
    ENGINE_INTELLIGENCE_FEEDBACK,
    FRAUD_CASE,
    AUDIT_EVENT,
    AUDIT_INTEGRITY,
    AUDIT_EXTERNAL_INTEGRITY,
    AUDIT_EVIDENCE_EXPORT,
    AUDIT_TRUST_ATTESTATION,
    AUDIT_DEGRADATION,
    DECISION_OUTBOX,
    REGULATED_MUTATION_COMMAND,
    TRUST_INCIDENT
}
