package com.frauddetection.alert.audit.read;

public enum ReadAccessResourceType {
    ALERT,
    FRAUD_CASE,
    SCORED_TRANSACTION,
    GOVERNANCE_ADVISORY,
    GOVERNANCE_ADVISORY_LIST,
    GOVERNANCE_ADVISORY_AUDIT,
    GOVERNANCE_ADVISORY_ANALYTICS,
    SYSTEM_TRUST_LEVEL,
    TRUST_INCIDENT,
    TRUST_INCIDENT_SIGNAL,
    AUDIT_EVENT,
    AUDIT_EVIDENCE_EXPORT,
    EXTERNAL_AUDIT_INTEGRITY,
    EXTERNAL_AUDIT_COVERAGE,
    REGULATED_MUTATION_COMMAND,
    REGULATED_MUTATION_RECOVERY,
    OUTBOX_RECOVERY,
    AUDIT_DEGRADATION
}
