package com.frauddetection.alert.regulated;

public enum RegulatedMutationState {
    REQUESTED,
    EVIDENCE_PREPARING,
    EVIDENCE_PREPARED,
    FINALIZING,
    FINALIZED_VISIBLE,
    FINALIZED_EVIDENCE_PENDING_EXTERNAL,
    FINALIZED_EVIDENCE_CONFIRMED,
    REJECTED_EVIDENCE_UNAVAILABLE,
    FAILED_BUSINESS_VALIDATION,
    FINALIZE_RECOVERY_REQUIRED,
    AUDIT_ATTEMPTED,
    BUSINESS_COMMITTING,
    BUSINESS_COMMITTED,
    SUCCESS_AUDIT_PENDING,
    SUCCESS_AUDIT_RECORDED,
    EVIDENCE_PENDING,
    EVIDENCE_CONFIRMED,
    COMMITTED,
    COMMITTED_DEGRADED,
    REJECTED,
    FAILED
}
