package com.frauddetection.scoring.orchestration;

public enum FraudScoringExecutionWarningCode {
    REQUIRED_ENGINE_NOT_AVAILABLE,
    OPTIONAL_ENGINE_NOT_AVAILABLE,
    ENGINE_EVALUATION_FAILURE_RECORDED,
    ENGINE_PUBLICATION_FAILURE_RECORDED,
    ENGINE_TIMEOUT_RECORDED,
    ENGINE_DEGRADED_RECORDED
}
