package com.frauddetection.alert.feedback;

public enum FraudFeedbackReasonCode {
    CUSTOMER_CONFIRMED_FRAUD,
    CUSTOMER_CONFIRMED_LEGITIMATE,
    DOCUMENTATION_CONFIRMED_FRAUD,
    DOCUMENTATION_CONFIRMED_LEGITIMATE,
    MERCHANT_CONFIRMED,
    CHARGEBACK_SIGNAL,
    ACCOUNT_TAKEOVER_INDICATOR,
    FALSE_POSITIVE_PATTERN,
    INSUFFICIENT_EVIDENCE,
    NEEDS_CUSTOMER_CONTACT,
    ANALYST_CONFIRMED_FRAUD,
    ANALYST_CONFIRMED_LEGITIMATE,
    ANALYST_INCONCLUSIVE,
    ANALYST_NEEDS_MORE_INFO
}
