package com.frauddetection.alert.engineintelligence;

public enum EngineIntelligenceProjectionDisposition {
    AUTHORITATIVE_OCCURRENCE_READY,
    BASELINE_OCCURRENCE_PENDING,
    STALE_OCCURRENCE,
    SOURCE_OCCURRENCE_PAYLOAD_CONFLICT,
    OPTIONAL_DIAGNOSTICS_ABSENT,
    TRANSIENT_STORAGE_UNAVAILABLE,
    PERMANENT_INVALID_DIAGNOSTICS
}
