package com.frauddetection.alert.engineintelligence;

public enum EngineIntelligenceProjectionOmissionReason {
    ENGINE_INTELLIGENCE_ABSENT,
    ENGINE_INTELLIGENCE_UNSUPPORTED_CONTRACT_VERSION,
    ENGINE_INTELLIGENCE_OVERSIZED,
    ENGINE_INTELLIGENCE_INVALID_SHAPE,
    ENGINE_INTELLIGENCE_REASON_CODE_NOT_ALLOWED,
    SCORING_OCCURRENCE_NOT_CURRENT,
    ENGINE_INTELLIGENCE_PROJECTION_FAILED
}
