package com.frauddetection.alert.regulated;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class Fdp40ResidualPlatformGapsTest {

    @Test
    void residualPlatformGapsAreExplicitForFutureHardening() throws Exception {
        String docs = Files.readString(Path.of("../docs/release/FDP-40-residual-platform-gaps.md"));

        List.of(
                "Real cosign/Sigstore verification",
                "Real SLSA provenance generated by the CI builder",
                "Registry immutability verified through provider API",
                "Branch protection verified through GitHub API",
                "Environment protection verified through GitHub or deployment platform API",
                "SBOM generation and vulnerability review",
                "Artifact retention and deletion controls",
                "Release approval audit export",
                "Promotion controller or policy-as-code enforcement",
                "Continuous drift detection for required checks and environment gates"
        ).forEach(item -> assertThat(docs).contains(item));

        assertThat(docs)
                .contains("required before production enablement")
                .contains("future enforcement work");
    }
}
