// GENERATED FILE - DO NOT EDIT MANUALLY.
// Source: alert-service/src/main/java/com/frauddetection/alert/security/authorization/AnalystAuthority.java

export const AUTHORITIES = Object.freeze({
  ALERT_READ: "alert:read",
  ASSISTANT_SUMMARY_READ: "assistant-summary:read",
  ALERT_DECISION_SUBMIT: "alert:decision:submit",
  FRAUD_CASE_READ: "fraud-case:read",
  FRAUD_CASE_AUDIT_READ: "fraud-case:audit:read",
  FRAUD_CASE_UPDATE: "fraud-case:update",
  TRANSACTION_MONITOR_READ: "transaction-monitor:read",
  ENGINE_INTELLIGENCE_FEEDBACK_READ: "engine-intelligence:feedback:read",
  ENGINE_INTELLIGENCE_FEEDBACK_WRITE: "engine-intelligence:feedback:write",
  GOVERNANCE_ADVISORY_AUDIT_WRITE: "governance-advisory:audit:write",
  SHADOW_PERFORMANCE_READ: "shadow-performance:read",
  AUDIT_READ: "audit:read",
  AUDIT_VERIFY: "audit:verify",
  AUDIT_EXPORT: "audit:export",
  AUDIT_DEGRADATION_RESOLVE: "audit-degradation:resolve",
  DECISION_OUTBOX_RECONCILE: "decision-outbox:reconcile",
  REGULATED_MUTATION_RECOVER: "regulated-mutation:recover",
  OUTBOX_INSPECT: "outbox:inspect",
  OUTBOX_RECOVER: "outbox:recover",
  OUTBOX_RESOLVE: "outbox:resolve",
  TRUST_INCIDENT_READ: "trust-incident:read",
  TRUST_INCIDENT_REFRESH: "trust-incident:refresh",
  TRUST_INCIDENT_ACK: "trust-incident:ack",
  TRUST_INCIDENT_RESOLVE: "trust-incident:resolve",
  SUSPICIOUS_TRANSACTION_READ: "suspicious-transaction:read",
});

export const AUTHORITY_VALUES = Object.freeze([
  "alert:read",
  "assistant-summary:read",
  "alert:decision:submit",
  "fraud-case:read",
  "fraud-case:audit:read",
  "fraud-case:update",
  "transaction-monitor:read",
  "engine-intelligence:feedback:read",
  "engine-intelligence:feedback:write",
  "governance-advisory:audit:write",
  "shadow-performance:read",
  "audit:read",
  "audit:verify",
  "audit:export",
  "audit-degradation:resolve",
  "decision-outbox:reconcile",
  "regulated-mutation:recover",
  "outbox:inspect",
  "outbox:recover",
  "outbox:resolve",
  "trust-incident:read",
  "trust-incident:refresh",
  "trust-incident:ack",
  "trust-incident:resolve",
  "suspicious-transaction:read",
]);
