package com.frauddetection.scoring.orchestration.aggregation;

public enum FraudEngineAggregationWarningCode {
    ENGINE_RESULT_LIMIT_APPLIED,
    REASON_CODE_NULL_DROPPED,
    REASON_CODE_BLANK_DROPPED,
    REASON_CODE_UNSUPPORTED_DROPPED,
    REASON_CODE_LIMIT_APPLIED,
    EVIDENCE_LIMIT_APPLIED,
    EVIDENCE_TEXT_TRUNCATED,
    EVIDENCE_UNSAFE_DROPPED,
    EVIDENCE_UNSUPPORTED_REASON_CODE_DROPPED,
    CONTRIBUTION_LIMIT_APPLIED,
    CONTRIBUTION_TEXT_TRUNCATED,
    CONTRIBUTION_UNSAFE_DROPPED,
    CONTRIBUTION_VALUE_DROPPED
}
