package com.frauddetection.alert.evidence;

public enum EvidenceProjectionState {
    PROJECTED,
    PARTIAL_MISSING_SOURCE_EVENT_ID,
    PARTIAL_MISSING_TRANSACTION_ID,
    PARTIAL_MISSING_CORRELATION_ID,
    PARTIAL_MISSING_REQUIRED_LINEAGE,
    PARTIAL_EMPTY_SCORING_EVIDENCE,
    PARTIAL_TRUNCATED,
    UNAVAILABLE_UNSUPPORTED_EVIDENCE,
    ERROR_PROJECTION_FAILED,
    LEGACY_NOT_PROJECTED
}
