package com.frauddetection.alert.api;

public enum FraudCaseTimelineEventType {
    FRAUD_CASE_CREATED,
    FRAUD_ALERT_LINKED,
    ALERT_EVIDENCE_SNAPSHOT_AVAILABLE,
    ALERT_EVIDENCE_SNAPSHOT_PARTIAL,
    ALERT_EVIDENCE_SNAPSHOT_UNAVAILABLE,
    LEGACY_CONTEXT
}
