package com.frauddetection.alert.api;

public enum SubmitDecisionOperationStatus {
    IN_PROGRESS,
    RECOVERY_REQUIRED,
    EVIDENCE_PREPARING,
    EVIDENCE_PREPARED,
    FINALIZING,
    FINALIZED_VISIBLE,
    FINALIZED_EVIDENCE_PENDING_EXTERNAL,
    FINALIZED_EVIDENCE_CONFIRMED,
    REJECTED_EVIDENCE_UNAVAILABLE,
    FAILED_BUSINESS_VALIDATION,
    FINALIZE_RECOVERY_REQUIRED
}
