package com.frauddetection.alert.api;

public enum SubmitDecisionOperationStatus {
    REJECTED_BEFORE_MUTATION,
    IN_PROGRESS,
    RECOVERY_REQUIRED,
    COMMIT_UNKNOWN,
    EVIDENCE_PREPARING,
    EVIDENCE_PREPARED,
    FINALIZING,
    FINALIZED_VISIBLE,
    FINALIZED_EVIDENCE_PENDING_EXTERNAL,
    FINALIZED_EVIDENCE_CONFIRMED,
    REJECTED_EVIDENCE_UNAVAILABLE,
    FAILED_BUSINESS_VALIDATION,
    FINALIZE_RECOVERY_REQUIRED,
    COMMITTED_EVIDENCE_PENDING,
    COMMITTED_EVIDENCE_CONFIRMED,
    COMMITTED_EVIDENCE_INCOMPLETE
}
